# Generated by Django 4.1.6 on 2023-02-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_member_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='gmt_offset',
        ),
    ]
