# Generated by Django 4.1.6 on 2023-02-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_member_time_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botignorechannels',
            name='channel_id',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guild_id',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
