# Generated by Django 4.1.7 on 2023-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_listofchoices_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessTheHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.CharField(max_length=18)),
                ('channel_id', models.CharField(max_length=18)),
                ('image_url', models.CharField(max_length=256)),
                ('hero_name', models.CharField(max_length=64)),
            ],
        ),
    ]
