# Generated by Django 4.2 on 2023-05-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_guessthehero_clue_count_guessthehero_guess_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botignorechannels',
            name='channel_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='guessthehero',
            name='guild_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='guessthehero',
            name='message_id',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='guessthehero',
            name='user_id',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guild_id',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
