# Generated by Django 4.2.1 on 2023-05-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_alter_botignorechannels_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spotify_authtoken',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='spotify_username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
