# Generated by Django 4.2.1 on 2023-06-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_alter_botignorechannels_channel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild')),
            ],
        ),
    ]
