# Generated by Django 4.2.1 on 2023-06-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_guildactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildactivity',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
