# Generated by Django 4.2.1 on 2023-06-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_guildactivity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildactivity',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
