# Generated by Django 4.2.1 on 2023-06-04 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_guildactivity_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildactivity',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guildactivity',
            name='nsfw_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MemberGuildActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('nsfw_count', models.IntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.member')),
            ],
        ),
    ]
