# Generated by Django 4.2.1 on 2023-06-15 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0026_memberguildactivity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightedGuildActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('activity', models.IntegerField(default=0)),
                ('startingMessage', models.CharField(max_length=32)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild')),
            ],
        ),
    ]
