# Generated by Django 4.2.1 on 2023-06-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0027_weightedguildactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildactivity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weightedguildactivity',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
