# Generated by Django 4.2.1 on 2023-06-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_weightedguildactivity_channeld_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightedguildactivity',
            old_name='channeld_id',
            new_name='channel_id',
        ),
    ]
