# Generated by Django 4.2.1 on 2023-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0030_rename_channeld_id_weightedguildactivity_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightedguildactivity',
            name='endingMessage',
            field=models.CharField(default='', max_length=32),
        ),
    ]
