# Generated by Django 4.2.1 on 2023-06-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_weightedguildactivity_endingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[(1, 'NSFW'), (2, 'Guess The Hero'), (3, 'Summary Ignore')], default=1, max_length=32)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild')),
            ],
        ),
    ]
