# Generated by Django 4.2.2 on 2023-06-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0032_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isGym',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MemberGymDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.member')),
            ],
        ),
    ]
