# Generated by Django 4.2.2 on 2023-07-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0033_member_isgym_membergymday'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergymday',
            name='isGym',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
