# Generated by Django 4.2.2 on 2023-07-06 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_membergymday_isgym'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gymCheckinTime',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
