# Generated by Django 4.2.2 on 2023-07-06 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0035_member_gymcheckintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
    ]
