# Generated by Django 4.2.3 on 2023-07-12 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_member_lastgymcheckindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
        migrations.CreateModel(
            name='MemberReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_text', models.CharField(default='', max_length=2048)),
                ('time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('frequency', models.DurationField(default=datetime.timedelta(0))),
                ('isComplete', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.member')),
            ],
        ),
    ]
