# Generated by Django 4.2.3 on 2023-07-14 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0037_alter_member_lastgymcheckindate_memberreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberreminder',
            name='target',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2023, 7, 14)),
        ),
    ]
