# Generated by Django 4.2.1 on 2023-11-14 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0038_memberreminder_target_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPlaylist',
            fields=[
                ('playlist_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('on_repeat', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2023, 11, 13)),
        ),
        migrations.CreateModel(
            name='PlaylistElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playlist', models.BooleanField(default=False)),
                ('on_repeat', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('duration', models.DurationField()),
                ('song_id', models.CharField(max_length=24)),
                ('source', models.CharField(choices=[('YOUTUBE', 'Youtube'), ('SPOTIFY', 'Spotify'), ('SOUNDCLOUD', 'Sound Cloud')], max_length=32)),
                ('order', models.PositiveIntegerField()),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.memberplaylist')),
            ],
        ),
        migrations.AddField(
            model_name='memberplaylist',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.member'),
        ),
    ]
