# Generated by Django 4.2.9 on 2024-02-05 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0039_memberplaylist_alter_member_lastgymcheckindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberreminder',
            name='origin_channel',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='memberreminder',
            name='origin_guild',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2024, 2, 4)),
        ),
        migrations.AlterField(
            model_name='memberreminder',
            name='target',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
