# Generated by Django 4.2.9 on 2024-03-15 23:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0041_complexfrequecy_alter_member_lastgymcheckindate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2024, 3, 15)),
        ),
        migrations.CreateModel(
            name='GameVersionSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.channel')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.gameversion')),
            ],
        ),
    ]
