# Generated by Django 4.2.9 on 2024-03-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0042_gameversion_alter_member_lastgymcheckindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameversion',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='version',
            field=models.CharField(default='', max_length=64),
        ),
    ]
