# Generated by Django 4.2.9 on 2024-10-01 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0043_alter_gameversion_name_alter_gameversion_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameversion',
            name='patchVersion',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2024, 10, 1)),
        ),
    ]
