# Generated by Django 4.2.17 on 2025-01-05 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0046_alter_gameversion_patchversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
    ]
