# Generated by Django 4.2.9

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0046_alter_gameversion_patchversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.TextField()),
                ('spotify_username', models.TextField(default='')),
                ('scope', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.member')),
            ],
        ),
    ]
