# Generated by Django 4.2.9 on 2025-03-08 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0046_alter_gameversion_patchversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2025, 3, 7)),
        ),
        migrations.CreateModel(
            name='GuildMealPrepping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(default='mon', max_length=3)),
                ('carbs', models.CharField(default='Rice, Pasta, Noodle, Bread, Potato, Any, None of them', max_length=2048)),
                ('protein', models.CharField(default='Beef, Pork, Chicken, Vegetarian, seafood, Safe, Beef, Pork, Chicken, seafood', max_length=2048)),
                ('bad', models.CharField(default='color is red, budget it 5 bucks, safe, color is green, Cant use stove, safe, Must have dairy, Include a dessert, Safe', max_length=2048)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.channel')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild')),
            ],
        ),
    ]
