# Generated by Django 4.2.17 on 2025-01-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0047_alter_member_lastgymcheckindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spotify',
            field=models.CharField(default='{}', max_length=1024),
        ),
    ]
