# Generated by Django 4.2.9 on 2025-03-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0047_alter_member_lastgymcheckindate_guildmealprepping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMealPrepperMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guildmealprepping')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.member')),
            ],
        ),
    ]
