# Generated by Django 4.2.9 on 2025-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0048_membermealpreppermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermealpreppermap',
            name='bad',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membermealpreppermap',
            name='carb',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membermealpreppermap',
            name='protein',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membermealpreppermap',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
