# Generated by Django 4.2.9 on 2025-03-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0049_membermealpreppermap_bad_membermealpreppermap_carb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermealpreppermap',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='membermealpreppermap',
            name='carb',
        ),
        migrations.RemoveField(
            model_name='membermealpreppermap',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='membermealpreppermap',
            name='retries',
        ),
        migrations.CreateModel(
            name='MMPMWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('retries', models.IntegerField(default=0)),
                ('carb', models.CharField(default='', max_length=64)),
                ('protein', models.CharField(default='', max_length=64)),
                ('bad', models.CharField(default='', max_length=64)),
                ('mmpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.membermealpreppermap')),
            ],
        ),
    ]
