# Generated by Django 4.2.9 on 2025-03-10 05:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0050_remove_membermealpreppermap_bad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildmealprepping',
            name='retries',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guildmealprepping',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild', unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastGymCheckinDate',
            field=models.DateField(default=datetime.date(2025, 3, 9)),
        ),
    ]
