# Generated by Django 4.2.9 on 2025-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0051_guildmealprepping_retries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.CharField(choices=[(1, 'NSFW'), (2, 'Guess The Hero'), (3, 'Summary Ignore'), (4, 'Meal prep')], default=1, max_length=32),
        ),
    ]
