# Generated by Django 4.2.9 on 2025-03-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0052_alter_channel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmealprepping',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.guild'),
        ),
    ]
