# Generated by Django 4.2.9 on 2025-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0053_alter_guildmealprepping_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmealprepping',
            name='day_of_week',
            field=models.CharField(default='mon', max_length=6),
        ),
    ]
