[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "discord_bot"
crate-type = ["cdylib"]

[dependencies]
librespot = "0.4.2"
