# Generated by Django 4.1.6 on 2023-02-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_timezone_gmt_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='nsfw_channel',
            field=models.CharField(blank=True, default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_zone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.timezone'),
        ),
    ]
