# Generated by Django 4.1.6 on 2023-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_guild_nsfw_channel_alter_member_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='time_format',
            field=models.CharField(default='%H:%M on %d-%m-%Y', max_length=64),
        ),
    ]
