# Generated by Django 4.1.7 on 2023-02-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_listofchoices_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofchoices',
            name='name',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
