# Generated by Django 4.1.7 on 2023-03-18 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_guessthehero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guessthehero',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='guessthehero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
