# Generated by Django 4.1.7 on 2023-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_guessthehero_guessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessthehero',
            name='message_id',
            field=models.CharField(default=None, max_length=18, null=True),
        ),
    ]
