# Generated by Django 4.2 on 2023-05-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_guessthehero_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessthehero',
            name='user_id',
            field=models.CharField(default=None, max_length=18, null=True),
        ),
    ]
