# Generated by Django 4.2 on 2023-05-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_guessthehero_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessthehero',
            name='clue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guessthehero',
            name='guess_count',
            field=models.IntegerField(default=0),
        ),
    ]
